
import axios from 'axios'

/**
 * ACTION TYPES
 */
const GET_SINGLE_PATH = 'GET_SINGLE_PATH'
const GET_PATHS_SINGLE_USER = 'GET_PATHS_SINGLE_USER'
const ADD_NEW_PATH = 'ADD_NEW_PATH'
const ADD_STEP_TO_PATH = 'ADD_STEP_TO_PATH'
const DELETE_SINGLE_PATH = 'DELETE_SINGLE_PATH'
const TOGGLE_PUBLIC = 'TOGGLE_PUBLIC'
const FOLLOW_PATH = 'FOLLOW_PATH'
const UNFOLLOW_PATH = 'UNFOLLOW_PATH'


const SET_ALL_PATHS_IN_CATEGORY = 'SET_ALL_PATHS_IN_CATEGORY'