
import axios from 'axios'

/**
 * ACTION TYPES
 */
const GET_STEP_COMPLETIONS_FOR_USER = 'GET_STEP_COMPLETIONS_FOR_USER'
const TOGGLE_STEP_COMPLETION = 'TOGGLE_STEP_COMPLETION'
const GET_STEP_RESOURCE = 'GET_STEP_RESOURCE'
const REMOVE_RESOURCE_FROM_STORE = 'REMOVE_RESOURCE_FROM_STORE'