const path = require('path')
const express = require('express')
const morgan = require('morgan')
const bodyParser = require('body-parser')
const compression = require('compression')
const sessionExpress = require('express-session')
const passport = require('passport')
const SequelizeStore = require('connect-session-sequelize')(sessionExpress.Store)
// const db = require('./db')
// const sessionStore = new SequelizeStore({db})
const PORT = process.env.PORT || 8080
const app = express()
const socketio = require('socket.io')
// const neo4j = require('neo4j-driver').v1;
// const driver = neo4j.driver("bolt://localhost", neo4j.auth.basic("neo4j", "1234"))
// const neoSession = driver.session();
const {session} = 